language: python

sudo: false

cache: pip

python:
'  - 3.6

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools wheel
  - pip wheel .
  - python setup.py install

script:
  - pytest tests

notifications:
  email: false

