language: python

python:
  - "2.7"
  - "3.5"

install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --only-binary=numpy,scipy numpy scipy"
  - "python setup.py install"

script:
  - "pytest"

notifications:
  email: false

