
class InputParameters(object):
    ALPHA = 'α'
    BETA = 'β'
    GAMMA = 'γ'

    VE = 'VE'
    VL = 'VL'
    VREV = 'Vrev'
    VI = 'VI'
    VTHR = 'Vthr'
    VRES = 'Vres'
    TAU_NMDA = 'τ_NMDA'
    TAU_NMDA_RISE = 'τ_NMDA_rise'
    TAU_GABA = 'τ_GABA'
    TAU_AMPA = 'τ_AMPA'
    TAU_RP = 'τ_rp'
    TAU = 'τ_m'
    CM = 'Cm'
    GM = 'gm'
    C_E = 'CE'
    C_I = 'CI'
    C_EXT = 'Cext'
    NU_EXT = 'nu_ext'
    G_AMPA = 'gAMPA'
    G_GABA = 'gGABA'
    G_NMDA = 'gNMDA'

    FRAC = 'frac'
    W = 'weight'

    TAU_RISE = 'tau_rise'
    TAU_D1 = 'tau_d1'
    TAU_D2 = 'tau_d2'

    TAU_F = 'τ_f'
    TAU_D = 'τ_d'
    U = 'U'

    MG = 'mg'
