
class PopulationParameters(object):
    GAMMA = 'γ'
    BETA = 'β'
    VE = 'VE'
    VL = 'VL'
    VI = 'VI'
    VTHR = 'Vthr'
    VRES = 'Vres'
    TAU_NMDA = 'τ_NMDA'
    TAU_NMDA_RISE = 'τ_NMDA_RISE'
    TAU_GABA = 'τ_GABA'
    TAU_AMPA = 'τ_AMPA'
    TAU_RP = 'τ_rp'
    TAU_M = 'τ_m'
    CM = 'Cm'
    GM = 'gm'
    C_E = 'CE'
    C_I = 'CI'
    C_EXT = 'Cext'
    NU_EXT = 'nu_ext'
    G_AMPA = 'gAMPA'
    G_GABA = 'gGABA'
    G_NMDA = 'gNMDA'
