
class SynapseParameters(object):
    GAMMA = 'gamma'
    BETA = 'beta'
    VE = 'VE'
    VL = 'VL'
    VI = 'VI'
    VTHR = 'Vthr'
    VRES = 'Vres'
    TAU_NMDA = 'tau_NMDA'
    TAU_NMDA_RISE = 'tau_NMDA_RISE'
    TAU_GABA = 'tau_GABA'
    TAU_AMPA = 'tau_AMPA'
    TAU_RP = 'tau_rp'
    TAU = 'tau_m'
    CM = 'Cm'
    GM = 'gm'
    C_E = 'CE'
    C_I = 'CI'
    C_EXT = 'Cext'
    NU_EXT = 'nu_ext'
    G_AMPA = 'gAMPA'
    G_GABA = 'gGABA'
    G_NMDA = 'gNMDA'

    FRAC = 'frac'
    W = 'weight'
